#!/usr/bin/env python3
"""
扩充球员数据库
生成100+球员数据，覆盖五大联赛主要球队
"""
import json
import os

# 球员模板：按球队分组
PLAYERS_BY_TEAM = {
    "man_city": [
        ("haaland", "厄林·哈兰德", "挪威", ["ST"], "left", {"pace":91,"shooting":93,"passing":66,"dribbling":80,"defending":45,"physical":88}, ["long_shot","header","power_header"], ["speed_burst","power_shot","clutch_player"]),
        ("de_bruyne", "凯文·德布劳内", "比利时", ["CAM","CM"], "right", {"pace":70,"shooting":86,"passing":93,"dribbling":86,"defending":64,"physical":78}, ["playmaker","long_shot","free_kick"], ["vision_pass","pinpoint_pass","curve_shot"]),
        ("rodrri", "罗德里", "西班牙", ["CDM","CM"], "right", {"pace":62,"shooting":75,"passing":85,"dribbling":78,"defending":82,"physical":85}, ["iron_wall","playmaker"], ["iron_wall","pinpoint_pass","interceptor"]),
        ("foden", "菲尔·福登", "英格兰", ["CAM","LW"], "left", {"pace":80,"shooting":82,"passing":84,"dribbling":88,"defending":55,"physical":65}, ["dribbling_master","playmaker"], ["ghost_dribble","vision_pass","first_touch"]),
        ("bernardo_silva", "贝尔纳多·席尔瓦", "葡萄牙", ["CAM","RW"], "right", {"pace":76,"shooting":80,"passing":86,"dribbling":90,"defending":60,"physical":68}, ["dribbling_master","playmaker"], ["ghost_dribble","endless_runner","first_touch"]),
        ("gvardiol", "约什科·格瓦迪奥尔", "克罗地亚", ["CB","LB"], "left", {"pace":78,"shooting":55,"passing":70,"dribbling":72,"defending":85,"physical":84}, ["iron_wall","header"], ["iron_wall","air_dominance","speed_burst"]),
        ("ruben_dias", "鲁本·迪亚斯", "葡萄牙", ["CB"], "right", {"pace":68,"shooting":50,"passing":72,"dribbling":70,"defending":90,"physical":88}, ["iron_wall","header","leader"], ["iron_wall","wall_defense","air_dominance"]),
        ("ederson", "埃德森", "巴西", ["GK"], "left", {"gk_diving":83,"gk_handling":82,"gk_kicking":93,"gk_reflexes":84,"gk_positioning":83}, ["sweeper_keeper","gk_distribution"], ["sweeper_keeper","gk_1v1_master","pinpoint_pass"]),
        ("walker", "凯尔·沃克", "英格兰", ["RB"], "right", {"pace":93,"shooting":60,"passing":75,"dribbling":75,"defending":80,"physical":82}, ["speedster","iron_wall"], ["speed_burst","fast_retreat","interceptor"]),
        ("gundogan", "伊尔凯·京多安", "德国", ["CM","CAM"], "right", {"pace":72,"shooting":82,"passing":86,"dribbling":84,"defending":68,"physical":72}, ["playmaker","clutch"], ["vision_pass","clutch_player","first_touch"]),
        ("alvarez", "胡利安·阿尔瓦雷斯", "阿根廷", ["ST","CF"], "right", {"pace":84,"shooting":85,"passing":78,"dribbling":84,"defending":50,"physical":72}, ["clutch","dribbling_master"], ["clutch_player","ghost_dribble","speed_burst"]),
        ("doku", "杰里米·多库", "比利时", ["LW","RW"], "right", {"pace":90,"shooting":72,"passing":75,"dribbling":89,"defending":40,"physical":65}, ["dribbling_master","speedster"], ["ghost_dribble","speed_burst","quick_turn"]),
        ("ake", "内森·阿克", "荷兰", ["CB","LB"], "left", {"pace":75,"shooting":45,"passing":68,"dribbling":68,"defending":83,"physical":80}, ["iron_wall"], ["iron_wall","fast_retreat","interceptor"]),
        ("stones", "约翰·斯通斯", "英格兰", ["CB","CDM"], "right", {"pace":70,"shooting":55,"passing":75,"dribbling":72,"defending":84,"physical":85}, ["iron_wall","playmaker"], ["iron_wall","pinpoint_pass","air_dominance"]),
        ("ortega", "斯特凡·奥尔特加", "德国", ["GK"], "right", {"gk_diving":80,"gk_handling":80,"gk_kicking":85,"gk_reflexes":81,"gk_positioning":80}, ["sweeper_keeper"], ["sweeper_keeper","gk_reflex_save"]),
    ],
    "real_madrid": [
        ("c_ronaldo", "克里斯蒂亚诺·罗纳尔多", "葡萄牙", ["LW","ST","RW"], "right", {"pace":88,"shooting":94,"passing":82,"dribbling":87,"defending":35,"physical":80}, ["long_shot","header","free_kick"], ["speed_burst","power_shot","clutch_player"]),
        ("mbappe", "基利安·姆巴佩", "法国", ["ST","LW"], "right", {"pace":97,"shooting":90,"passing":80,"dribbling":92,"defending":36,"physical":78}, ["speedster","dribbling_master","clutch"], ["speed_burst","ghost_dribble","clutch_player"]),
        ("bellingham", "祖德·贝林厄姆", "英格兰", ["CAM","CM"], "right", {"pace":80,"shooting":85,"passing":84,"dribbling":87,"defending":75,"physical":82}, ["playmaker","clutch","box_to_box"], ["vision_pass","clutch_player","ghost_dribble"]),
        ("vinicius", "维尼修斯·儒尼奥尔", "巴西", ["LW"], "right", {"pace":95,"shooting":83,"passing":78,"dribbling":90,"defending":30,"physical":68}, ["dribbling_master","speedster"], ["ghost_dribble","speed_burst","quick_turn"]),
        ("rodrygo", "罗德里戈", "巴西", ["RW","LW"], "right", {"pace":89,"shooting":82,"passing":78,"dribbling":86,"defending":35,"physical":65}, ["dribbling_master","clutch"], ["ghost_dribble","clutch_player","speed_burst"]),
        ("modric", "卢卡·莫德里奇", "克罗地亚", ["CM","CAM"], "right", {"pace":70,"shooting":78,"passing":89,"dribbling":87,"defending":65,"physical":65}, ["playmaker","dribbling_master"], ["vision_pass","ghost_dribble","endless_runner"]),
        ("kroos", "托尼·克罗斯", "德国", ["CM","CDM"], "left", {"pace":58,"shooting":82,"passing":91,"dribbling":82,"defending":70,"physical":70}, ["playmaker","long_shot","pinpoint_pass"], ["pinpoint_pass","vision_pass","curve_shot"]),
        ("valverde", "费德里科·巴尔韦德", "乌拉圭", ["CM","RM"], "right", {"pace":85,"shooting":84,"passing":83,"dribbling":82,"defending":78,"physical":85}, ["box_to_box","long_shot"], ["speed_burst","power_shot","endless_runner"]),
        ("courtois", "蒂博·库尔图瓦", "比利时", ["GK"], "left", {"gk_diving":87,"gk_handling":86,"gk_kicking":82,"gk_reflexes":88,"gk_positioning":85}, ["gk_saver","gk_1v1"], ["gk_reflex_save","gk_1v1_master","wall_defense"]),
        ("rüdiger", "安东尼奥·吕迪格", "德国", ["CB"], "right", {"pace":82,"shooting":50,"passing":72,"dribbling":68,"defending":88,"physical":88}, ["iron_wall","header","speedster"], ["iron_wall","air_dominance","speed_burst"]),
        ("militao", "埃德尔·米利唐", "巴西", ["CB"], "right", {"pace":85,"shooting":50,"passing":72,"dribbling":70,"defending":87,"physical":85}, ["iron_wall","speedster"], ["iron_wall","speed_burst","interceptor"]),
        ("carvajal", "达尼·卡瓦哈尔", "西班牙", ["RB"], "right", {"pace":80,"shooting":65,"passing":80,"dribbling":80,"defending":82,"physical":75}, ["crossing","iron_wall"], ["pinpoint_pass","interceptor","endless_runner"]),
        ("mendy", "费兰·门迪", "法国", ["LB"], "right", {"pace":85,"shooting":55,"passing":75,"dribbling":78,"defending":82,"physical":80}, ["speedster","iron_wall"], ["speed_burst","fast_retreat","interceptor"]),
        ("camavinga", "爱德华多·卡马文加", "法国", ["CM","LB"], "left", {"pace":82,"shooting":70,"passing":80,"dribbling":84,"defending":76,"physical":80}, ["box_to_box","dribbling_master"], ["speed_burst","ghost_dribble","endless_runner"]),
        ("tchouameni", "奥雷利安·楚阿梅尼", "法国", ["CDM","CB"], "right", {"pace":72,"shooting":70,"passing":80,"dribbling":76,"defending":85,"physical":88}, ["iron_wall","header"], ["iron_wall","air_dominance","interceptor"]),
    ],
    "barcelona": [
        ("messi", "利昂内尔·梅西", "阿根廷", ["RW","CF","CAM"], "left", {"pace":85,"shooting":92,"passing":91,"dribbling":95,"defending":35,"physical":65}, ["dribbling_master","playmaker","free_kick"], ["ghost_dribble","vision_pass","curve_shot"]),
        ("lewandowski", "罗伯特·莱万多夫斯基", "波兰", ["ST"], "right", {"pace":78,"shooting":91,"passing":79,"dribbling":84,"defending":45,"physical":82}, ["header","clutch","poacher"], ["power_shot","air_dominance","clutch_player"]),
        ("gavi", "巴勃罗·加维", "西班牙", ["CM","CAM"], "right", {"pace":75,"shooting":72,"passing":80,"dribbling":83,"defending":70,"physical":68}, ["playmaker","box_to_box"], ["endless_runner","vision_pass","mad_dog"]),
        ("pedri", "佩德里", "西班牙", ["CM","CAM"], "right", {"pace":73,"shooting":75,"passing":86,"dribbling":87,"defending":60,"physical":62}, ["playmaker","dribbling_master"], ["vision_pass","ghost_dribble","first_touch"]),
        ("de_jong", "弗伦基·德容", "荷兰", ["CM","CDM"], "right", {"pace":80,"shooting":70,"passing":85,"dribbling":89,"defending":75,"physical":80}, ["dribbling_master","playmaker"], ["ghost_dribble","vision_pass","endless_runner"]),
        ("raphinha", "拉菲尼亚", "巴西", ["RW","LW"], "left", {"pace":85,"shooting":80,"passing":80,"dribbling":84,"defending":45,"physical":68}, ["dribbling_master","crossing"], ["ghost_dribble","pinpoint_pass","speed_burst"]),
        ("ter_stegen", "马克-安德烈·特尔施特根", "德国", ["GK"], "right", {"gk_diving":85,"gk_handling":84,"gk_kicking":90,"gk_reflexes":86,"gk_positioning":84}, ["sweeper_keeper","gk_distribution"], ["sweeper_keeper","gk_reflex_save","pinpoint_pass"]),
        ("araujo", "罗纳德·阿劳霍", "乌拉圭", ["CB"], "right", {"pace":88,"shooting":50,"passing":70,"dribbling":70,"defending":87,"physical":88}, ["iron_wall","speedster","header"], ["iron_wall","speed_burst","air_dominance"]),
        ("kounde", "朱尔·孔德", "法国", ["CB","RB"], "right", {"pace":82,"shooting":55,"passing":75,"dribbling":78,"defending":85,"physical":80}, ["iron_wall","speedster"], ["iron_wall","speed_burst","interceptor"]),
        ("balde", "亚历杭德罗·巴尔德", "西班牙", ["LB"], "right", {"pace":92,"shooting":55,"passing":72,"dribbling":80,"defending":75,"physical":72}, ["speedster","crossing"], ["speed_burst","fast_retreat","pinpoint_pass"]),
        ("christensen", "安德烈亚斯·克里斯滕森", "丹麦", ["CB"], "right", {"pace":72,"shooting":50,"passing":75,"dribbling":70,"defending":84,"physical":82}, ["iron_wall","playmaker"], ["iron_wall","pinpoint_pass","interceptor"]),
        ("ferran", "费兰·托雷斯", "西班牙", ["ST","RW"], "right", {"pace":84,"shooting":78,"passing":75,"dribbling":80,"defending":45,"physical":72}, ["speedster"], ["speed_burst","clutch_player"]),
        ("yamal", "拉明·亚马尔", "西班牙", ["RW"], "left", {"pace":87,"shooting":76,"passing":80,"dribbling":88,"defending":40,"physical":60}, ["dribbling_master","playmaker"], ["ghost_dribble","vision_pass","quick_turn"]),
        (" Cancelo", "若昂·坎塞洛", "葡萄牙", ["LB","RB"], "right", {"pace":80,"shooting":70,"passing":84,"dribbling":86,"defending":76,"physical":72}, ["crossing","dribbling_master"], ["pinpoint_pass","ghost_dribble","endless_runner"]),
        (" Cancelo", "若昂·坎塞洛", "葡萄牙", ["LB","RB"], "right", {"pace":80,"shooting":70,"passing":84,"dribbling":86,"defending":76,"physical":72}, ["crossing","dribbling_master"], ["pinpoint_pass","ghost_dribble","endless_runner"]),
    ],
    "bayern_munich": [
        ("kane", "哈里·凯恩", "英格兰", ["ST"], "right", {"pace":70,"shooting":93,"passing":84,"dribbling":83,"defending":47,"physical":83}, ["long_shot","header","playmaker"], ["power_shot","vision_pass","air_dominance"]),
        ("musiala", "贾马尔·穆西亚拉", "德国", ["CAM","LW"], "right", {"pace":85,"shooting":80,"passing":82,"dribbling":91,"defending":50,"physical":65}, ["dribbling_master","playmaker"], ["ghost_dribble","quick_turn","vision_pass"]),
        ("sane", "勒鲁瓦·萨内", "德国", ["RW","LW"], "right", {"pace":92,"shooting":80,"passing":80,"dribbling":86,"defending":40,"physical":72}, ["speedster","dribbling_master"], ["speed_burst","ghost_dribble","curve_shot"]),
        ("kimmich", "约书亚·基米希", "德国", ["CDM","CM"], "right", {"pace":70,"shooting":78,"passing":88,"dribbling":82,"defending":80,"physical":75}, ["playmaker","crossing","iron_wall"], ["pinpoint_pass","vision_pass","interceptor"]),
        ("davies", "阿方索·戴维斯", "加拿大", ["LB"], "right", {"pace":96,"shooting":65,"passing":76,"dribbling":82,"defending":78,"physical":75}, ["speedster","crossing"], ["speed_burst","fast_retreat","pinpoint_pass"]),
        ("neuer", "曼努埃尔·诺伊尔", "德国", ["GK"], "right", {"gk_diving":84,"gk_handling":85,"gk_kicking":93,"gk_reflexes":85,"gk_positioning":87}, ["sweeper_keeper","gk_leader","gk_distribution"], ["sweeper_keeper","gk_1v1_master","gk_reflex_save"]),
        ("upamecano", "达约·于帕梅卡诺", "法国", ["CB"], "right", {"pace":85,"shooting":45,"passing":70,"dribbling":72,"defending":85,"physical":87}, ["iron_wall","speedster","header"], ["iron_wall","speed_burst","air_dominance"]),
        ("de_ligt", "马泰斯·德里赫特", "荷兰", ["CB"], "right", {"pace":75,"shooting":55,"passing":72,"dribbling":70,"defending":88,"physical":88}, ["iron_wall","header","leader"], ["iron_wall","air_dominance","wall_defense"]),
        ("gnabry", "塞尔日·格纳布里", "德国", ["RW","LW"], "right", {"pace":85,"shooting":82,"passing":78,"dribbling":84,"defending":45,"physical":72}, ["dribbling_master","long_shot"], ["ghost_dribble","power_shot","curve_shot"]),
        ("muller", "托马斯·穆勒", "德国", ["CF","CAM"], "right", {"pace":68,"shooting":82,"passing":82,"dribbling":80,"defending":60,"physical":75}, ["playmaker","clutch","poacher"], ["vision_pass","clutch_player","smart_positioning"]),
        ("goretzka", "莱昂·戈雷茨卡", "德国", ["CM","CDM"], "right", {"pace":78,"shooting":78,"passing":80,"dribbling":80,"defending":78,"physical":85}, ["box_to_box","header"], ["speed_burst","air_dominance","endless_runner"]),
        ("coman", "金斯利·科曼", "法国", ["LW","RW"], "right", {"pace":93,"shooting":75,"passing":76,"dribbling":87,"defending":35,"physical":65}, ["speedster","dribbling_master"], ["speed_burst","ghost_dribble","quick_turn"]),
    ],
    "liverpool": [
        ("salah", "穆罕默德·萨拉赫", "埃及", ["RW","ST"], "left", {"pace":89,"shooting":87,"passing":81,"dribbling":88,"defending":45,"physical":75}, ["speedster","dribbling_master","clutch"], ["speed_burst","ghost_dribble","clutch_player"]),
        ("vandijk", "维尔吉尔·范戴克", "荷兰", ["CB"], "right", {"pace":78,"shooting":60,"passing":74,"dribbling":72,"defending":90,"physical":90}, ["iron_wall","header","leader"], ["iron_wall","air_dominance","wall_defense"]),
        ("mac_allister", "亚历克西斯·麦卡利斯特", "阿根廷", ["CM","CDM"], "right", {"pace":72,"shooting":78,"passing":84,"dribbling":82,"defending":72,"physical":72}, ["playmaker","long_shot"], ["vision_pass","pinpoint_pass","curve_shot"]),
        ("nunez", "达尔文·努涅斯", "乌拉圭", ["ST"], "right", {"pace":91,"shooting":80,"passing":70,"dribbling":78,"defending":40,"physical":80}, ["speedster","header"], ["speed_burst","air_dominance","power_shot"]),
        ("diaz", "路易斯·迪亚斯", "哥伦比亚", ["LW"], "right", {"pace":88,"shooting":78,"passing":75,"dribbling":86,"defending":40,"physical":68}, ["speedster","dribbling_master"], ["speed_burst","ghost_dribble","quick_turn"]),
        ("szoboszlai", "多米尼克·索博斯洛伊", "匈牙利", ["CM","CAM"], "right", {"pace":80,"shooting":82,"passing":82,"dribbling":82,"defending":65,"physical":75}, ["long_shot","playmaker"], ["power_shot","vision_pass","curve_shot"]),
        ("alisson", "阿利松·贝克尔", "巴西", ["GK"], "right", {"gk_diving":85,"gk_handling":85,"gk_kicking":87,"gk_reflexes":86,"gk_positioning":86}, ["sweeper_keeper","gk_1v1","gk_saver"], ["sweeper_keeper","gk_1v1_master","gk_reflex_save"]),
        ("arnold", "特伦特·亚历山大-阿诺德", "英格兰", ["RB"], "right", {"pace":76,"shooting":75,"passing":90,"dribbling":80,"defending":76,"physical":72}, ["crossing","playmaker","long_shot"], ["pinpoint_pass","vision_pass","curve_shot"]),
        ("robertson", "安德鲁·罗伯逊", "苏格兰", ["LB"], "left", {"pace":80,"shooting":65,"passing":82,"dribbling":80,"defending":80,"physical":75}, ["crossing","iron_wall"], ["pinpoint_pass","endless_runner","interceptor"]),
        ("gakpo", "科迪·加克波", "荷兰", ["LW","ST"], "right", {"pace":85,"shooting":78,"passing":76,"dribbling":82,"defending":50,"physical":75}, ["speedster"], ["speed_burst","ghost_dribble","power_shot"]),
        ("gravenberch", "瑞恩·赫拉芬贝赫", "荷兰", ["CM","CDM"], "right", {"pace":78,"shooting":70,"passing":80,"dribbling":85,"defending":70,"physical":80}, ["dribbling_master","playmaker"], ["ghost_dribble","vision_pass","first_touch"]),
        ("konate", "易卜拉希马·科纳特", "法国", ["CB"], "right", {"pace":85,"shooting":45,"passing":70,"dribbling":70,"defending":85,"physical":87}, ["iron_wall","speedster","header"], ["iron_wall","speed_burst","air_dominance"]),
    ],
    "psg": [
        ("dembele", "乌斯曼·登贝莱", "法国", ["RW","LW"], "right", {"pace":90,"shooting":75,"passing":80,"dribbling":88,"defending":40,"physical":65}, ["dribbling_master","speedster"], ["ghost_dribble","speed_burst","quick_turn"]),
        ("asensio", "马尔科·阿森西奥", "西班牙", ["CAM","RW"], "left", {"pace":80,"shooting":82,"passing":80,"dribbling":84,"defending":50,"physical":72}, ["long_shot","dribbling_master"], ["curve_shot","ghost_dribble","power_shot"]),
        ("hakimi", "阿什拉夫·哈基米", "摩洛哥", ["RB"], "right", {"pace":95,"shooting":70,"passing":78,"dribbling":82,"defending":78,"physical":75}, ["speedster","crossing"], ["speed_burst","pinpoint_pass","fast_retreat"]),
        ("vitinha", "维蒂尼亚", "葡萄牙", ["CM"], "right", {"pace":78,"shooting":72,"passing":85,"dribbling":86,"defending":68,"physical":65}, ["playmaker","dribbling_master"], ["vision_pass","ghost_dribble","first_touch"]),
        ("donnarumma", "詹路易吉·多纳鲁马", "意大利", ["GK"], "right", {"gk_diving":88,"gk_handling":85,"gk_kicking":78,"gk_reflexes":87,"gk_positioning":84}, ["gk_saver","gk_1v1"], ["gk_reflex_save","gk_1v1_master","wall_defense"]),
        ("marquinhos", "马尔基尼奥斯", "巴西", ["CB","CDM"], "right", {"pace":82,"shooting":50,"passing":78,"dribbling":75,"defending":87,"physical":82}, ["iron_wall","speedster"], ["iron_wall","speed_burst","interceptor"]),
        ("hernandez", "卢卡斯·埃尔南德斯", "法国", ["CB","LB"], "right", {"pace":80,"shooting":50,"passing":72,"dribbling":72,"defending":85,"physical":85}, ["iron_wall","speedster"], ["iron_wall","speed_burst","interceptor"]),
        ("ruiz", "法比安·鲁伊斯", "西班牙", ["CM","CAM"], "left", {"pace":75,"shooting":78,"passing":84,"dribbling":82,"defending":70,"physical":78}, ["playmaker","long_shot"], ["vision_pass","curve_shot","endless_runner"]),
        ("kolo_muani", "兰达尔·科洛·穆阿尼", "法国", ["ST","LW"], "right", {"pace":88,"shooting":80,"passing":75,"dribbling":84,"defending":45,"physical":75}, ["speedster","dribbling_master"], ["speed_burst","ghost_dribble","clutch_player"]),
        ("barcola", "布拉德利·巴尔科拉", "法国", ["LW","RW"], "right", {"pace":90,"shooting":70,"passing":72,"dribbling":84,"defending":35,"physical":62}, ["speedster","dribbling_master"], ["speed_burst","ghost_dribble","quick_turn"]),
        ("zaire_emery", "沃伦·扎伊尔-埃梅里", "法国", ["CM"], "right", {"pace":76,"shooting":72,"passing":80,"dribbling":82,"defending":70,"physical":70}, ["playmaker","box_to_box"], ["vision_pass","endless_runner","first_touch"]),
        ("skriniar", "米兰·什克里尼亚尔", "斯洛伐克", ["CB"], "right", {"pace":72,"shooting":50,"passing":72,"dribbling":68,"defending":87,"physical":88}, ["iron_wall","header"], ["iron_wall","air_dominance","wall_defense"]),
    ],
    "inter_milan": [
        ("lautaro", "劳塔罗·马丁内斯", "阿根廷", ["ST"], "right", {"pace":82,"shooting":88,"passing":75,"dribbling":84,"defending":50,"physical":78}, ["clutch","poacher","header"], ["clutch_player","air_dominance","power_shot"]),
        ("barella", "尼科洛·巴雷拉", "意大利", ["CM","CAM"], "right", {"pace":80,"shooting":78,"passing":84,"dribbling":84,"defending":75,"physical":78}, ["box_to_box","playmaker"], ["endless_runner","vision_pass","mad_dog"]),
        ("thuram", "马库斯·图拉姆", "法国", ["ST","LW"], "right", {"pace":85,"shooting":82,"passing":75,"dribbling":82,"defending":45,"physical":85}, ["speedster","header"], ["speed_burst","air_dominance","power_shot"]),
        ("calhanoglu", "哈坎·恰尔汗奥卢", "土耳其", ["CDM","CM"], "right", {"pace":70,"shooting":85,"passing":88,"dribbling":82,"defending":72,"physical":72}, ["long_shot","playmaker","free_kick"], ["power_shot","vision_pass","curve_shot"]),
        ("bastoni", "亚历山德罗·巴斯托尼", "意大利", ["CB"], "left", {"pace":75,"shooting":50,"passing":80,"dribbling":75,"defending":86,"physical":82}, ["iron_wall","playmaker"], ["iron_wall","pinpoint_pass","interceptor"]),
        ("dimarco", "费德里科·迪马尔科", "意大利", ["LB","LWB"], "left", {"pace":80,"shooting":78,"passing":82,"dribbling":80,"defending":78,"physical":72}, ["crossing","long_shot"], ["pinpoint_pass","curve_shot","speed_burst"]),
        ("sommer", "扬·索默", "瑞士", ["GK"], "right", {"gk_diving":83,"gk_handling":84,"gk_kicking":82,"gk_reflexes":85,"gk_positioning":85}, ["gk_saver","gk_1v1"], ["gk_reflex_save","gk_1v1_master"]),
        ("acerbi", "弗朗切斯科·阿切尔比", "意大利", ["CB"], "right", {"pace":65,"shooting":50,"passing":72,"dribbling":68,"defending":85,"physical":85}, ["iron_wall","header"], ["iron_wall","air_dominance","wall_defense"]),
        ("dumfries", "丹泽尔·邓弗里斯", "荷兰", ["RB","RWB"], "right", {"pace":85,"shooting":70,"passing":75,"dribbling":76,"defending":80,"physical":85}, ["speedster","crossing","header"], ["speed_burst","pinpoint_pass","air_dominance"]),
        ("mkitaryan", "亨里克·姆希塔良", "亚美尼亚", ["CM","CAM"], "right", {"pace":72,"shooting":75,"passing":82,"dribbling":82,"defending":65,"physical":68}, ["playmaker","dribbling_master"], ["vision_pass","ghost_dribble","first_touch"]),
        ("frattesi", "达维德·弗拉泰西", "意大利", ["CM"], "right", {"pace":78,"shooting":76,"passing":76,"dribbling":78,"defending":72,"physical":78}, ["box_to_box"], ["endless_runner","speed_burst","clutch_player"]),
        ("pavard", "邦雅曼·帕瓦尔", "法国", ["CB","RB"], "right", {"pace":75,"shooting":65,"passing":75,"dribbling":72,"defending":85,"physical":82}, ["iron_wall","long_shot"], ["iron_wall","curve_shot","interceptor"]),
    ],
    "man_united": [
        ("bruno_fernandes", "布鲁诺·费尔南德斯", "葡萄牙", ["CAM","CM"], "right", {"pace":75,"shooting":85,"passing":89,"dribbling":84,"defending":65,"physical":75}, ["playmaker","long_shot","free_kick"], ["vision_pass","power_shot","pinpoint_pass"]),
        ("rashford", "马库斯·拉什福德", "英格兰", ["LW","ST"], "right", {"pace":90,"shooting":82,"passing":75,"dribbling":84,"defending":42,"physical":75}, ["speedster","dribbling_master"], ["speed_burst","ghost_dribble","power_shot"]),
        ("garnacho", "亚历杭德罗·加纳乔", "阿根廷", ["LW","RW"], "right", {"pace":88,"shooting":75,"passing":72,"dribbling":82,"defending":40,"physical":65}, ["speedster","dribbling_master"], ["speed_burst","ghost_dribble","quick_turn"]),
        ("casemiro", "卡塞米罗", "巴西", ["CDM"], "right", {"pace":65,"shooting":75,"passing":78,"dribbling":75,"defending":88,"physical":90}, ["iron_wall","header","leader"], ["iron_wall","air_dominance","wall_defense"]),
        ("martinez", "利桑德罗·马丁内斯", "阿根廷", ["CB"], "left", {"pace":72,"shooting":50,"passing":78,"dribbling":75,"defending":85,"physical":80}, ["iron_wall","leader"], ["iron_wall","interceptor","mad_dog"]),
        ("onana", "安德烈·奥纳纳", "喀麦隆", ["GK"], "right", {"gk_diving":82,"gk_handling":82,"gk_kicking":88,"gk_reflexes":83,"gk_positioning":82}, ["sweeper_keeper","gk_distribution"], ["sweeper_keeper","gk_1v1_master","pinpoint_pass"]),
        ("mainoo", "科比·梅努", "英格兰", ["CM"], "right", {"pace":75,"shooting":70,"passing":80,"dribbling":82,"defending":72,"physical":72}, ["playmaker","dribbling_master"], ["vision_pass","ghost_dribble","first_touch"]),
        ("maguire", "哈里·马奎尔", "英格兰", ["CB"], "right", {"pace":62,"shooting":50,"passing":72,"dribbling":68,"defending":82,"physical":88}, ["iron_wall","header"], ["iron_wall","air_dominance","wall_defense"]),
        ("dalot", "迪奥戈·达洛特", "葡萄牙", ["RB","LB"], "right", {"pace":82,"shooting":65,"passing":78,"dribbling":80,"defending":80,"physical":75}, ["crossing","iron_wall"], ["pinpoint_pass","speed_burst","interceptor"]),
        ("mctominay", "斯科特·麦克托米奈", "苏格兰", ["CM","CDM"], "right", {"pace":72,"shooting":75,"passing":72,"dribbling":72,"defending":75,"physical":85}, ["box_to_box","header"], ["air_dominance","endless_runner","power_shot"]),
        ("hojlund", "拉斯穆斯·霍伊伦德", "丹麦", ["ST"], "left", {"pace":85,"shooting":78,"passing":68,"dribbling":76,"defending":45,"physical":80}, ["speedster","header"], ["speed_burst","air_dominance","clutch_player"]),
        ("mount", "梅森·芒特", "英格兰", ["CAM","CM"], "right", {"pace":78,"shooting":75,"passing":80,"dribbling":82,"defending":65,"physical":70}, ["playmaker","box_to_box"], ["vision_pass","endless_runner","first_touch"]),
    ],
    "arsenal": [
        ("saka", "布卡约·萨卡", "英格兰", ["RW"], "left", {"pace":85,"shooting":82,"passing":82,"dribbling":86,"defending":55,"physical":72}, ["dribbling_master","crossing","clutch"], ["ghost_dribble","pinpoint_pass","clutch_player"]),
        ("odegaard", "马丁·厄德高", "挪威", ["CAM","CM"], "left", {"pace":75,"shooting":82,"passing":88,"dribbling":86,"defending":55,"physical":65}, ["playmaker","dribbling_master"], ["vision_pass","ghost_dribble","curve_shot"]),
        ("rice", "德克兰·赖斯", "英格兰", ["CDM","CM"], "left", {"pace":78,"shooting":75,"passing":82,"dribbling":80,"defending":85,"physical":85}, ["iron_wall","box_to_box","leader"], ["iron_wall","endless_runner","vision_pass"]),
        ("haaland2", "加布里埃尔·马加良斯", "巴西", ["CB"], "left", {"pace":72,"shooting":55,"passing":70,"dribbling":68,"defending":86,"physical":88}, ["iron_wall","header"], ["iron_wall","air_dominance","wall_defense"]),
        ("saliba", "威廉·萨利巴", "法国", ["CB"], "right", {"pace":82,"shooting":50,"passing":72,"dribbling":72,"defending":87,"physical":85}, ["iron_wall","speedster"], ["iron_wall","speed_burst","interceptor"]),
        ("white", "本·怀特", "英格兰", ["RB"], "right", {"pace":80,"shooting":60,"passing":78,"dribbling":78,"defending":82,"physical":78}, ["iron_wall","crossing"], ["interceptor","pinpoint_pass","endless_runner"]),
        ("zinchenko", "亚历山大·津琴科", "乌克兰", ["LB","CM"], "left", {"pace":72,"shooting":65,"passing":82,"dribbling":82,"defending":75,"physical":70}, ["playmaker","dribbling_master"], ["vision_pass","ghost_dribble","pinpoint_pass"]),
        ("raya", "戴维·拉亚", "西班牙", ["GK"], "right", {"gk_diving":80,"gk_handling":80,"gk_kicking":85,"gk_reflexes":82,"gk_positioning":81}, ["sweeper_keeper","gk_distribution"], ["sweeper_keeper","gk_reflex_save","pinpoint_pass"]),
        ("martinelli", "加布里埃尔·马丁内利", "巴西", ["LW"], "right", {"pace":89,"shooting":78,"passing":72,"dribbling":84,"defending":45,"physical":70}, ["speedster","dribbling_master"], ["speed_burst","ghost_dribble","quick_turn"]),
        ("havertz", "凯·哈弗茨", "德国", ["ST","CAM"], "left", {"pace":80,"shooting":80,"passing":78,"dribbling":82,"defending":55,"physical":82}, ["header","clutch"], ["air_dominance","clutch_player","vision_pass"]),
        ("jorginho", "若日尼奥", "意大利", ["CDM","CM"], "right", {"pace":62,"shooting":70,"passing":85,"dribbling":80,"defending":75,"physical":70}, ["playmaker","iron_wall"], ["pinpoint_pass","vision_pass","interceptor"]),
        ("trossard", "莱安德罗·特罗萨德", "比利时", ["LW","ST"], "left", {"pace":78,"shooting":78,"passing":76,"dribbling":82,"defending":50,"physical":68}, ["dribbling_master","clutch"], ["ghost_dribble","clutch_player","curve_shot"]),
    ],
    "chelsea": [
        ("palmer", "科尔·帕尔默", "英格兰", ["CAM","RW"], "left", {"pace":78,"shooting":82,"passing":84,"dribbling":85,"defending":50,"physical":68}, ["playmaker","clutch","long_shot"], ["vision_pass","clutch_player","curve_shot"]),
        ("jackson", "尼古拉斯·杰克逊", "塞内加尔", ["ST"], "right", {"pace":86,"shooting":76,"passing":68,"dribbling":78,"defending":40,"physical":78}, ["speedster"], ["speed_burst","ghost_dribble","power_shot"]),
        ("caicedo", "莫伊塞斯·凯塞多", "厄瓜多尔", ["CDM"], "right", {"pace":75,"shooting":65,"passing":80,"dribbling":78,"defending":85,"physical":82}, ["iron_wall","interceptor"], ["iron_wall","interceptor","endless_runner"]),
        ("enzo_fernandez", "恩佐·费尔南德斯", "阿根廷", ["CM","CDM"], "right", {"pace":72,"shooting":75,"passing":84,"dribbling":80,"defending":75,"physical":75}, ["playmaker","long_shot"], ["vision_pass","curve_shot","pinpoint_pass"]),
        ("sterling", "拉希姆·斯特林", "英格兰", ["LW","RW"], "right", {"pace":88,"shooting":75,"passing":78,"dribbling":86,"defending":42,"physical":68}, ["speedster","dribbling_master"], ["speed_burst","ghost_dribble","quick_turn"]),
        ("gallagher", "康纳·加拉格尔", "英格兰", ["CM"], "right", {"pace":78,"shooting":72,"passing":76,"dribbling":76,"defending":75,"physical":78}, ["box_to_box"], ["endless_runner","mad_dog","speed_burst"]),
        ("disasi", "阿克塞尔·迪萨西", "法国", ["CB"], "right", {"pace":75,"shooting":50,"passing":70,"dribbling":68,"defending":83,"physical":85}, ["iron_wall","header"], ["iron_wall","air_dominance","wall_defense"]),
        ("colwill", "利维·科尔威尔", "英格兰", ["CB","LB"], "left", {"pace":72,"shooting":50,"passing":72,"dribbling":70,"defending":82,"physical":82}, ["iron_wall","leader"], ["iron_wall","interceptor","wall_defense"]),
        ("james", "里斯·詹姆斯", "英格兰", ["RB"], "right", {"pace":82,"shooting":75,"passing":82,"dribbling":82,"defending":82,"physical":82}, ["crossing","iron_wall","leader"], ["pinpoint_pass","interceptor","endless_runner"]),
        ("cucurella", "马克·库库雷利亚", "西班牙", ["LB"], "right", {"pace":78,"shooting":60,"passing":78,"dribbling":80,"defending":78,"physical":68}, ["crossing","dribbling_master"], ["pinpoint_pass","ghost_dribble","endless_runner"]),
        ("mudryk", "米哈伊洛·穆德里克", "乌克兰", ["LW"], "right", {"pace":93,"shooting":68,"passing":70,"dribbling":82,"defending":35,"physical":62}, ["speedster","dribbling_master"], ["speed_burst","ghost_dribble","quick_turn"]),
        ("sanchez", "罗伯特·桑切斯", "西班牙", ["GK"], "right", {"gk_diving":80,"gk_handling":80,"gk_kicking":85,"gk_reflexes":80,"gk_positioning":80}, ["sweeper_keeper"], ["sweeper_keeper","gk_reflex_save"]),
    ],
    "atletico_madrid": [
        ("griezmann", "安托万·格列兹曼", "法国", ["ST","CF","CAM"], "left", {"pace":78,"shooting":85,"passing":84,"dribbling":86,"defending":55,"physical":72}, ["playmaker","clutch","poacher"], ["vision_pass","clutch_player","ghost_dribble"]),
        ("morata", "阿尔瓦罗·莫拉塔", "西班牙", ["ST"], "right", {"pace":82,"shooting":80,"passing":72,"dribbling":76,"defending":45,"physical":80}, ["header","speedster"], ["air_dominance","speed_burst","clutch_player"]),
        ("koke", "科克", "西班牙", ["CM","CDM"], "right", {"pace":72,"shooting":72,"passing":82,"dribbling":78,"defending":78,"physical":78}, ["iron_wall","playmaker","leader"], ["interceptor","vision_pass","endless_runner"]),
        ("de_paul", "罗德里戈·德保罗", "阿根廷", ["CM","CAM"], "right", {"pace":76,"shooting":75,"passing":82,"dribbling":80,"defending":70,"physical":75}, ["playmaker","box_to_box"], ["vision_pass","endless_runner","pinpoint_pass"]),
        ("lemar", "托马斯·勒马尔", "法国", ["LW","CAM"], "left", {"pace":78,"shooting":72,"passing":80,"dribbling":84,"defending":50,"physical":65}, ["dribbling_master","playmaker"], ["ghost_dribble","vision_pass","first_touch"]),
        ("oblak", "扬·奥布拉克", "斯洛文尼亚", ["GK"], "right", {"gk_diving":86,"gk_handling":85,"gk_kicking":82,"gk_reflexes":86,"gk_positioning":87}, ["gk_saver","gk_1v1"], ["gk_reflex_save","gk_1v1_master","wall_defense"]),
        ("gimenez", "何塞·玛丽亚·希门尼斯", "乌拉圭", ["CB"], "right", {"pace":75,"shooting":50,"passing":70,"dibbling":68,"defending":87,"physical":85}, ["iron_wall","header"], ["iron_wall","air_dominance","wall_defense"]),
        ("savic", "斯特凡·萨维奇", "黑山", ["CB"], "right", {"pace":68,"shooting":50,"passing":70,"dribbling":68,"defending":85,"physical":85}, ["iron_wall","header"], ["iron_wall","air_dominance","wall_defense"]),
        ("llorente", "马科斯·略伦特", "西班牙", ["CM","RB"], "right", {"pace":82,"shooting":75,"passing":78,"dribbling":78,"defending":78,"physical":82}, ["box_to_box","speedster"], ["speed_burst","endless_runner","interceptor"]),
        ("molina", "纳韦尔·莫利纳", "阿根廷", ["RB"], "right", {"pace":82,"shooting":65,"passing":75,"dribbling":76,"defending":78,"physical":75}, ["crossing","speedster"], ["pinpoint_pass","speed_burst","interceptor"]),
        ("correa", "安赫尔·科雷亚", "阿根廷", ["ST","RW"], "right", {"pace":80,"shooting":75,"passing":75,"dribbling":82,"defending":45,"physical":72}, ["dribbling_master","clutch"], ["ghost_dribble","clutch_player","quick_turn"]),
        ("witsel", "阿克塞尔·维特塞尔", "比利时", ["CB","CDM"], "right", {"pace":60,"shooting":65,"passing":78,"dribbling":72,"defending":82,"physical":82}, ["iron_wall","playmaker"], ["iron_wall","vision_pass","interceptor"]),
    ],
    "juventus": [
        ("vlahovic", "杜尚·弗拉霍维奇", "塞尔维亚", ["ST"], "right", {"pace":80,"shooting":86,"passing":70,"dribbling":78,"defending":45,"physical":82}, ["header","long_shot","power_shot"], ["power_shot","air_dominance","curve_shot"]),
        ("chiesa", "费德里科·基耶萨", "意大利", ["RW","LW","ST"], "right", {"pace":87,"shooting":80,"passing":76,"dribbling":84,"defending":50,"physical":72}, ["speedster","dribbling_master"], ["speed_burst","ghost_dribble","power_shot"]),
        ("rabiot", "阿德里安·拉比奥", "法国", ["CM"], "left", {"pace":78,"shooting":75,"passing":80,"dribbling":80,"defending":75,"physical":82}, ["box_to_box","header"], ["endless_runner","air_dominance","vision_pass"]),
        ("locatelli", "曼努埃尔·洛卡特利", "意大利", ["CM","CDM"], "right", {"pace":70,"shooting":72,"passing":80,"dribbling":76,"defending":78,"physical":78}, ["playmaker","iron_wall"], ["vision_pass","interceptor","pinpoint_pass"]),
        ("bremer", "格莱松·布雷默", "巴西", ["CB"], "left", {"pace":78,"shooting":50,"passing":70,"dribbling":68,"defending":87,"physical":87}, ["iron_wall","header"], ["iron_wall","air_dominance","wall_defense"]),
        ("danilo", "达尼洛", "巴西", ["CB","RB"], "right", {"pace":75,"shooting":55,"passing":75,"dribbling":75,"defending":84,"physical":82}, ["iron_wall","leader"], ["iron_wall","interceptor","endless_runner"]),
        ("szczesny", "沃伊切赫·什琴斯尼", "波兰", ["GK"], "right", {"gk_diving":85,"gk_handling":84,"gk_kicking":82,"gk_reflexes":85,"gk_positioning":85}, ["gk_saver","gk_1v1"], ["gk_reflex_save","gk_1v1_master","wall_defense"]),
        ("cambiaso", "安德烈亚·坎比亚索", "意大利", ["LB","RB"], "right", {"pace":78,"shooting":65,"passing":78,"dribbling":80,"defending":78,"physical":72}, ["crossing","dribbling_master"], ["pinpoint_pass","ghost_dribble","endless_runner"]),
        ("mckennie", "韦斯顿·麦肯尼", "美国", ["CM"], "right", {"pace":75,"shooting":70,"passing":75,"dribbling":75,"defending":75,"physical":82}, ["box_to_box","header"], ["endless_runner","air_dominance","mad_dog"]),
        ("yildiz", "凯南·伊尔迪兹", "土耳其", ["CAM","LW"], "right", {"pace":82,"shooting":72,"passing":76,"dribbling":84,"defending":40,"physical":65}, ["dribbling_master"], ["ghost_dribble","quick_turn","vision_pass"]),
        ("gatti", "费德里科·加蒂", "意大利", ["CB"], "right", {"pace":72,"shooting":50,"passing":68,"dribbling":68,"defending":82,"physical":82}, ["iron_wall","header"], ["iron_wall","air_dominance","interceptor"]),
        ("costic", "菲利普·科斯蒂奇", "塞尔维亚", ["LW","LB"], "left", {"pace":78,"shooting":65,"passing":82,"dribbling":80,"defending":70,"physical":72}, ["crossing","speedster"], ["pinpoint_pass","speed_burst","endless_runner"]),
    ],
    "dortmund": [
        ("reus", "马尔科·罗伊斯", "德国", ["CAM","LW"], "right", {"pace":78,"shooting":82,"passing":84,"dribbling":85,"defending":50,"physical":68}, ["dribbling_master","playmaker","free_kick"], ["ghost_dribble","vision_pass","curve_shot"]),
        ("brandt", "尤利安·布兰特", "德国", ["CAM","LW"], "right", {"pace":80,"shooting":78,"passing":84,"dribbling":85,"defending":50,"physical":68}, ["playmaker","dribbling_master"], ["vision_pass","ghost_dribble","first_touch"]),
        ("hummels", "马茨·胡梅尔斯", "德国", ["CB"], "right", {"pace":62,"shooting":60,"passing":80,"dribbling":72,"defending":85,"physical":82}, ["iron_wall","playmaker","header"], ["iron_wall","vision_pass","air_dominance"]),
        ("reier", "卡里姆·阿德耶米", "德国", ["RW","ST"], "right", {"pace":94,"shooting":72,"passing":70,"dribbling":82,"defending":40,"physical":68}, ["speedster","dribbling_master"], ["speed_burst","ghost_dribble","quick_turn"]),
        ("sabitzer", "马塞尔·萨比策", "奥地利", ["CM","CAM"], "right", {"pace":75,"shooting":78,"passing":80,"dribbling":78,"defending":68,"physical":72}, ["long_shot","playmaker"], ["power_shot","vision_pass","curve_shot"]),
        ("schlotterbeck", "尼科·施洛特贝克", "德国", ["CB"], "right", {"pace":75,"shooting":50,"passing":72,"dribbling":70,"defending":84,"physical":82}, ["iron_wall","speedster"], ["iron_wall","speed_burst","interceptor"]),
        ("ryerson", "朱利安·吕尔森", "挪威", ["RB"], "right", {"pace":82,"shooting":60,"passing":72,"dribbling":74,"defending":78,"physical":75}, ["speedster","iron_wall"], ["speed_burst","interceptor","endless_runner"]),
        ("maehlen", "尼克拉斯·聚勒", "德国", ["CB"], "right", {"pace":70,"shooting":55,"passing":72,"dribbling":70,"defending":85,"physical":88}, ["iron_wall","header"], ["iron_wall","air_dominance","wall_defense"]),
        ("fullkrug", "尼克拉斯·菲尔克鲁格", "德国", ["ST"], "right", {"pace":68,"shooting":82,"passing":70,"dribbling":72,"defending":45,"physical":82}, ["header","poacher"], ["air_dominance","clutch_player","power_shot"]),
        ("gittens", "杰米·拜诺-吉滕斯", "英格兰", ["LW","RW"], "right", {"pace":88,"shooting":68,"passing":68,"dribbling":82,"defending":35,"physical":62}, ["speedster","dribbling_master"], ["speed_burst","ghost_dribble","quick_turn"]),
        ("can", "埃姆雷·詹", "德国", ["CM","CDM","CB"], "right", {"pace":72,"shooting":72,"passing":78,"dribbling":76,"defending":78,"physical":82}, ["iron_wall","box_to_box"], ["iron_wall","endless_runner","interceptor"]),
        ("kobel", "格雷戈尔·科贝尔", "瑞士", ["GK"], "right", {"gk_diving":82,"gk_handling":82,"gk_kicking":82,"gk_reflexes":83,"gk_positioning":82}, ["gk_saver"], ["gk_reflex_save","gk_1v1_master"]),
    ],
    "ac_milan": [
        ("leao", "拉斐尔·莱奥", "葡萄牙", ["LW","ST"], "right", {"pace":93,"shooting":80,"passing":78,"dribbling":88,"defending":40,"physical":78}, ["speedster","dribbling_master"], ["speed_burst","ghost_dribble","quick_turn"]),
        ("pulisc", "克里斯蒂安·普利西奇", "美国", ["RW","LW"], "right", {"pace":85,"shooting":78,"passing":78,"dribbling":84,"defending":45,"physical":68}, ["dribbling_master","speedster"], ["ghost_dribble","speed_burst","curve_shot"]),
        ("theo", "特奥·埃尔南德斯", "法国", ["LB"], "right", {"pace":90,"shooting":75,"passing":78,"dribbling":82,"defending":80,"physical":82}, ["speedster","crossing","header"], ["speed_burst","pinpoint_pass","air_dominance"]),
        ("maignan", "迈尼昂", "法国", ["GK"], "right", {"gk_diving":85,"gk_handling":84,"gk_kicking":85,"gk_reflexes":86,"gk_positioning":85}, ["sweeper_keeper","gk_saver"], ["sweeper_keeper","gk_reflex_save","gk_1v1_master"]),
        ("tomori", "菲卡约·托莫里", "英格兰", ["CB"], "right", {"pace":85,"shooting":50,"passing":72,"dribbling":72,"defending":84,"physical":82}, ["iron_wall","speedster"], ["iron_wall","speed_burst","interceptor"]),
        ("reijnders", "泰贾尼·雷因德斯", "荷兰", ["CM"], "right", {"pace":78,"shooting":72,"passing":80,"dribbling":80,"defending":72,"physical":75}, ["playmaker","box_to_box"], ["vision_pass","endless_runner","first_touch"]),
        ("bennacer", "伊斯梅尔·本纳塞尔", "阿尔及利亚", ["CM","CDM"], "left", {"pace":72,"shooting":70,"passing":82,"dribbling":82,"defending":75,"physical":68}, ["playmaker","dribbling_master"], ["vision_pass","ghost_dribble","interceptor"]),
        ("chukwueze", "萨穆埃尔·丘库埃泽", "尼日利亚", ["RW"], "right", {"pace":88,"shooting":72,"passing":72,"dribbling":84,"defending":40,"physical":68}, ["speedster","dribbling_master"], ["speed_burst","ghost_dribble","quick_turn"]),
        ("giroud", "奥利维耶·吉鲁", "法国", ["ST"], "left", {"pace":68,"shooting":82,"passing":72,"dribbling":75,"defending":45,"physical":85}, ["header","poacher","clutch"], ["air_dominance","clutch_player","wall_defense"]),
        ("loftus_cheek", "鲁本·洛夫图斯-奇克", "英格兰", ["CM","CAM"], "right", {"pace":80,"shooting":75,"passing":76,"dribbling":82,"defending":70,"physical":82}, ["box_to_box","dribbling_master"], ["ghost_dribble","endless_runner","speed_burst"]),
        ("kjaer", "西蒙·克亚尔", "丹麦", ["CB"], "right", {"pace":65,"shooting":50,"passing":70,"dribbling":68,"defending":84,"physical":85}, ["iron_wall","header","leader"], ["iron_wall","air_dominance","wall_defense"]),
        ("calabria", "戴维德·卡拉布里亚", "意大利", ["RB"], "right", {"pace":78,"shooting":60,"passing":75,"dribbling":76,"defending":80,"physical":75}, ["iron_wall","crossing"], ["interceptor","pinpoint_pass","endless_runner"]),
    ],
    "tottenham": [
        ("son", "孙兴慜", "韩国", ["LW","ST"], "right", {"pace":87,"shooting":87,"passing":82,"dribbling":86,"defending":42,"physical":70}, ["speedster","dribbling_master","clutch"], ["speed_burst","ghost_dribble","clutch_player"]),
        ("maddison", "詹姆斯·麦迪逊", "英格兰", ["CAM"], "right", {"pace":75,"shooting":80,"passing":85,"dribbling":84,"defending":50,"physical":68}, ["playmaker","dribbling_master","free_kick"], ["vision_pass","ghost_dribble","curve_shot"]),
        ("romero", "克里斯蒂安·罗梅罗", "阿根廷", ["CB"], "right", {"pace":75,"shooting":50,"passing":70,"dribbling":68,"defending":86,"physical":85}, ["iron_wall","header","leader"], ["iron_wall","air_dominance","mad_dog"]),
        ("vandeven", "米基·范德文", "荷兰", ["CB"], "right", {"pace":90,"shooting":45,"passing":68,"dribbling":68,"defending":82,"physical":82}, ["iron_wall","speedster"], ["iron_wall","speed_burst","interceptor"]),
        ("bentancur", "罗德里戈·本坦库尔", "乌拉圭", ["CM","CDM"], "right", {"pace":72,"shooting":70,"passing":80,"dribbling":78,"defending":78,"physical":80}, ["playmaker","box_to_box"], ["vision_pass","endless_runner","interceptor"]),
        ("vicario", "古列尔莫·维卡里奥", "意大利", ["GK"], "right", {"gk_diving":82,"gk_handling":82,"gk_kicking":82,"gk_reflexes":83,"gk_positioning":82}, ["gk_saver"], ["gk_reflex_save","gk_1v1_master"]),
        ("porro", "佩德罗·波罗", "西班牙", ["RB"], "right", {"pace":82,"shooting":70,"passing":78,"dribbling":80,"defending":75,"physical":72}, ["crossing","speedster"], ["pinpoint_pass","speed_burst","endless_runner"]),
        ("u dog", "德斯蒂尼·乌多吉", "意大利", ["LB"], "right", {"pace":85,"shooting":60,"passing":72,"dribbling":78,"defending":75,"physical":72}, ["speedster","crossing"], ["speed_burst","pinpoint_pass","endless_runner"]),
        ("kulusevski", "德扬·库卢塞夫斯基", "瑞典", ["RW","CAM"], "right", {"pace":80,"shooting":75,"passing":80,"dribbling":84,"defending":55,"physical":78}, ["dribbling_master","playmaker"], ["ghost_dribble","vision_pass","first_touch"]),
        ("richarlison", "里沙利松", "巴西", ["ST","LW"], "right", {"pace":82,"shooting":76,"passing":70,"dribbling":78,"defending":45,"physical":78}, ["header","speedster"], ["air_dominance","speed_burst","clutch_player"]),
        ("sarr", "帕普·萨尔", "塞内加尔", ["CM","CDM"], "right", {"pace":78,"shooting":65,"passing":75,"dribbling":76,"defending":75,"physical":78}, ["box_to_box"], ["endless_runner","interceptor","speed_burst"]),
        ("dragusin", "拉杜·德拉古辛", "罗马尼亚", ["CB"], "right", {"pace":75,"shooting":45,"passing":68,"dribbling":68,"defending":82,"physical":82}, ["iron_wall"], ["iron_wall","interceptor","wall_defense"]),
    ],
}

def generate_players_json():
    players = {}
    for team_id, team_players in PLAYERS_BY_TEAM.items():
        for p in team_players:
            pid = p[0]
            # 清理重复的player_id
            if pid in players:
                pid = pid + "_" + team_id
            players[pid] = {
                "name": p[1],
                "short_name": p[1][:3] if len(p[1]) > 3 else p[1],
                "nationality": p[2],
                "positions": p[3],
                "preferred_foot": p[4],
                "attributes": p[5],
                "traits": p[6],
                "skills": p[7],
                "career": [{"club": team_id, "years": "现役"}],
            }
    return {"players": players}

if __name__ == "__main__":
    data = generate_players_json()
    output_path = os.path.join(os.path.dirname(__file__), "..", "data", "players.json")
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"已生成 {len(data['players'])} 名球员到 {output_path}")
